name: CloudFormation lint action
author: ryof <ryo.furuyama@gmail.com>
description: CloudFormation lint action using cfn-lint
runs:
  using: docker
  image: Dockerfile
branding:
  icon: check-circle
  color: green